SELECT * FROM Lancamentos
SELECT * FROM Usuarios
SELECT * FROM Naturezas
SELECT * FROM Produtos
SELECT * FROM Filial
SELECT * FROM LancamentosProdutos
SELECT CASE F.TIPO WHEN 0 THEN 'PAGAR' WHEN 1 THEN 'RECEBER' END TIPO,* FROM Financeiro F 
INNER JOIN NATUREZAS N ON N.Codigo=F.CodNatureza
INNER JOIN FILIAL FI ON FI.Codigo=F.CodFilial
INNER JOIN USUARIOS U ON U.CODIGO = F.CodUsuario
WHERE F.Vencimento BETWEEN '2020-01-01' AND  '2020-03-31' 
AND F.DataPagamento  BETWEEN '2020-01-01' AND  '2020-03-31'
AND F.CodLancamento = ''
AND F.Codigo = ''
AND F.CodNatureza = ''
and F.Tipo IN ('PAGAR','RECEBER')

--INSERT INTO Financeiro VALUES (1,1,29,'Lancamento: 29-VENDA2 COM FINANCEIRO SEM BAIXA','2020-03-20',115.0,NULL,NULL,1,1)

SELECT L.Codigo IDLANCAMENTO,CONVERT(DATE,L.Data,23) EMISSAO,L.VALOR VL_TOTAL,L.CodUsuario IDUSUARIO,U.Nome USUARIO,
L.CODFILIAL IDFILIAL,F.Nome FILIAL,L.CODNATUREZA IDNATUREZA,N.Nome NATUREZA,L.OBSERVACAO, 
LP.Codigo SEQIDPRODUTO,P.Codigo IDPRODUTO,P.Nome PRODUTO,CONVERT(NUMERIC(16,2),LP.Valor/LP.Quantidade) VL_UNIT,
LP.Quantidade,LP.Valor VL_TT_PROD
FROM Lancamentos L
INNER JOIN LancamentosProdutos LP ON LP.CODLANCAMENTO=L.CODIGO
INNER JOIN Produtos P ON P.Codigo=LP.CodProduto
INNER JOIN NATUREZAS N ON N.Codigo=L.CodNatureza
INNER JOIN FILIAL F ON F.Codigo=L.CodFilial
INNER JOIN Usuarios U ON U.Codigo=L.CodUsuario
WHERE L.Codigo = ''

SELECT CASE F.TIPO WHEN 0 THEN 'PAGAR' WHEN 1 THEN 'RECEBER' END TIPO,F.CodNatureza IDNATUREZA,N.NOME NATUREZA,
F.Vencimento DT_VENCIMENTO,F.Valor VALOR,F.DataPagamento DT_PAGAMENTO,F.ValorPago VL_PAGO,F.CodUsuario IDUSUARIO,U.NOME USUARIO,F.CodFilial IDFILIAL,FI.Nome FILIAL 
FROM Financeiro F 
INNER JOIN NATUREZAS N ON N.Codigo=F.CodNatureza
INNER JOIN FILIAL FI ON FI.Codigo=F.CodFilial
INNER JOIN USUARIOS U ON U.CODIGO = F.CodUsuario